### ISSUE TITLE
what are those underlines and true,false hints

### ISSUE THREAD

**Issue by laoshaw** [Freed-Wu/bitbake-language-server#11]
I switched from language-server-bitbake to bitbake-language-server because it's now the default in coc.nvim etc, but I got extra info and it's quite verbose, screenshot below, why are so many underlines and true/false?

![image](https://github.com/user-attachments/assets/aa3b0340-c2cf-4705-8a8d-d2a58d5d9096)

**Comment by laoshaw** [comment]
below is from language-server-bitbake which is very quiet:
![image](https://github.com/user-attachments/assets/30561d3a-3f88-4d76-822f-71b45f2636d5)

**Comment by Freed-Wu** [comment]
It comes from oelint-adv https://github.com/priv-kweihmann/oelint-adv

**Comment by laoshaw** [comment]
> It comes from oelint-adv https://github.com/priv-kweihmann/oelint-adv

language-server-bitbake also uses oelint-adv though, but it does not have those verbose info

**Comment by Freed-Wu** [comment]
IRRI, language-server-bitbake use tree-sitter, not oelint-adv.

**Comment by Freed-Wu** [comment]
BTW, This feature (oelint-adv) is added in #6 and #7.

**Comment by Freed-Wu** [comment]
oelint-adv introduces breaking API changes results in these weird information.
