### ISSUE TITLE
Go to definition not implemented

### ISSUE THREAD

**Issue by rustand2** [Freed-Wu/bitbake-language-server#3]
Hello, I'm trying to use this in emacs, but I'm getting an error saying that the server does not support the method textDocument/definition. I feel like this is the main feature needed by a language server for bitbake, to avoid constantly needing to use ag/grep to find package definitions.

**Comment by Freed-Wu** [comment]
Yes, It need more works to make it available.

Currently, this LS uses [tree-sitter-bitbake](https://github.com/amaanq/tree-sitter-bitbake) to parse bitbake to get AST. Perhaps [oelint-parser](https://github.com/priv-kweihmann/oelint-parser) will be a better choice. In conclusion, perhaps there will be a large change in the future.

**Comment by Freed-Wu** [comment]
BTW, if anyone is curious how to realize goto defintion/references, [here](https://github.com/Freed-Wu/autotools-language-server) is a reference.

**Comment by Freed-Wu** [comment]
Related issue: https://github.com/priv-kweihmann/oelint-parser/issues/127

**Comment by Freed-Wu** [comment]
I've refactored the code. This is a demo video: <https://asciinema.org/a/628560>

![628560](https://github.com/Freed-Wu/bitbake-language-server/assets/32936898/5720403e-7bf4-436c-91aa-578482a7ba07)

Is it you need?
